package org.example.demo1.mybatis.model;

public class Publisher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @return the value of PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.ID
     *
     * @param id the value for PUBLIC.PUBLISHER.ID
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @return the value of PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PUBLISHER.NAME
     *
     * @param name the value for PUBLIC.PUBLISHER.NAME
     *
     * @mbg.generated Mon Apr 15 20:34:58 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}